spring:
  application:
    name: zb-financial

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: emItc3ByaW5nLWJvb3QtZGl2aWRlbmQtcHJvamVjdC10dXRvcfvae2fEKeGAEGfwefs3mlhbC1qd3Qtc2VjcmV0Cg

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"